language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

before_script:
    - phpversion=$(phpenv version); if [[ $phpversion =~ 5\.3\.3.* ]]; then composer install --dev --prefer-source; else composer install --dev; fi;    
